name: Continuous Deployment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm test
    - run: npm run lint
    - run: npm run build
    - name: Store dist folder
      uses: actions/upload-artifact@v4
      with:
        name: dist-artifact
        path: dist/

  terraform:
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download dist artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-artifact
        path: ../dist

    - name: Verify dist folder contents
      run: |
        echo "Contents of ../dist:"
        ls -R ../dist

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: eu-north-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6  # Adjust to your Terraform version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan (File Deployment Only)
      run: terraform plan -target=aws_s3_object.react_app_files

    - name: Terraform Apply (File Deployment Only)
      run: terraform apply -target=aws_s3_object.react_app_files -auto-approve
